"use client";
import {useEffect,useRef,useState} from 'react';
import {ShieldCheck,LayoutDashboard,FileCheck2,Radio,History,ArrowUpRight,Download,RefreshCw,Play,ChevronRight,Check,AlertTriangle} from 'lucide-react';
import {Button} from '@/components/ui/button';
type Row=Record<string,any>;
const nav=[['Overview',LayoutDashboard],['Rule review',FileCheck2],['Source evidence',Radio],['Audit trail',History]] as const;
const label=(s:string)=>s?.replaceAll('_',' ').toLowerCase();
const money=(n:any)=>n==null?'—':Number(n).toFixed(2);
function Badge({value}:{value:string}){return <span className={'badge '+value?.toLowerCase()}>{label(value)}</span>}
export default function Home(){
 const [tab,setTab]=useState('Overview'),[mode,setMode]=useState('live'),[date,setDate]=useState('2026-09-21');
 const [data,setData]=useState<Row|null>(null),[busy,setBusy]=useState('Starting Python engine…'),[error,setError]=useState('');
 const [selected,setSelected]=useState<string|null>(null),[note,setNote]=useState(''),[filter,setFilter]=useState('ALL'),[employee,setEmployee]=useState<Row|null>(null),[page,setPage]=useState(0),[saved,setSaved]=useState('');
 const py=useRef<any>(null),files=useRef<Row>({}),revision=useRef(0),lock=useRef(false),ready=useRef(false);
 async function save(next:Row){const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:revision.current,files:next})});const o=await r.json();if(!r.ok)throw new Error(o.error);revision.current=o.revision;setSaved(new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));}
 async function compute(action:string,args:Row={},workspace=mode,day=date){py.current.globals.set('request_json',JSON.stringify({action,mode:workspace,evaluation_date:day,...args}));return JSON.parse(await py.current.runPythonAsync('dispatch(request_json)'));}
 async function run(action:string,args:Row={},workspace=mode,day=date){
  if(lock.current||!ready.current)return;lock.current=true;setBusy(action==='monitor'?'Checking both government sources…':'Evaluating and saving evidence…');setError('');
  try{if(action==='monitor'){const r=await fetch('/api/sources');const b=await r.json();if(!r.ok)throw new Error(b.error);args={sources:b.sources};}const o=await compute(action,args,workspace,day);if(action!=='view')await save(o.files);files.current=o.files;setData(o.view);setMode(workspace);setDate(day);setPage(0);}
  catch(e:any){setError(e.message+' Your last saved evidence is preserved. Reload before retrying if a save failed.');if(py.current)await compute('restore',{files:files.current}).catch(()=>{});}
  finally{lock.current=false;setBusy('');}
 }
 useEffect(()=>{let active=true;(async()=>{try{
  const loadRuntime=new Promise<any>((resolve,reject)=>{if((window as any).loadPyodide){resolve({loadPyodide:(window as any).loadPyodide});return;}const script=document.createElement('script');script.src='/pyodide/pyodide.js';script.onload=()=>resolve({loadPyodide:(window as any).loadPyodide});script.onerror=()=>reject(new Error('Python runtime download failed'));document.head.appendChild(script);});
  const [boot,session,loader]=await Promise.all([fetch('/bootstrap.json').then(r=>r.json()),fetch('/api/session').then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error);return v;}),loadRuntime]);
  const runtime=await loader.loadPyodide({indexURL:'/pyodide/'});if(!active)return;py.current=runtime;runtime.FS.mkdirTree('/app/atlas_compliance');runtime.FS.mkdirTree('/runtime');
  await Promise.all(boot.modules.map(async(name:string)=>{const r=await fetch(`/engine/${name}.py`);if(!r.ok)throw new Error('Python module unavailable');runtime.FS.writeFile(`/app/atlas_compliance/${name}.py`,await r.text());}));
  runtime.globals.set('bootstrap_json',JSON.stringify(boot));await runtime.runPythonAsync("import sys,os,json\nsys.path.insert(0,'/app')\nos.chdir('/runtime')\nfrom atlas_compliance.webbridge import configure,dispatch\nconfigure(json.loads(bootstrap_json))");
  revision.current=session.revision;files.current=session.files||{};const out=await compute('restore',{files:files.current},'live','2026-09-21');if(!session.revision)await save(out.files);files.current=out.files;if(active){setData(out.view);setBusy('');ready.current=true;}
 }catch(e:any){if(active){setError('Could not open workspace: '+e.message);setBusy('');}}})();return()=>{active=false;};},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const c=new AbortController();Promise.resolve(context.registerTool({name:'read_compliance_summary',description:'Read the visible compliance summary for the selected workspace and evaluation date.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||Object.keys(input).length)throw new Error('No arguments accepted');if(!data)throw new Error('Workspace is loading');return{mode,date,summary:data.decision_summary,pending:data.proposals.filter((p:Row)=>p.status==='REVIEW_REQUIRED').length};}},{signal:c.signal})).catch(()=>{});return()=>c.abort();},[data,mode,date]);
 function download(name:string,value:any){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
 const pending=data?.proposals.filter((p:Row)=>p.status==='REVIEW_REQUIRED')||[],proposal=data?.proposals.find((p:Row)=>p.proposal_id===selected),rows=(data?.results||[]).filter((r:Row)=>filter==='ALL'||r.decision_state===filter),summary=data?.decision_summary||{};
 const exposure=(data?.results||[]).reduce((n:number,r:Row)=>n+Number(r.estimated_weekly_underpayment||0),0),blocked=!!busy||!data;
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><ShieldCheck size={24}/></span>atlas<span className="brand-period">.</span></a><div className="workspace-label">COMPLIANCE WORKSPACE</div><nav>{nav.map(([name,Icon])=><button key={name} className={'nav-item '+(tab===name?'active':'')} onClick={()=>{setTab(name);setEmployee(null)}}><Icon size={19}/>{name}{name==='Rule review'&&pending.length>0&&<span className="nav-count">{pending.length}</span>}</button>)}</nav><div className="sidebar-bottom"><span className="country-mark">A</span><div><strong>Asteria</strong><span>Fictional jurisdiction · AST</span></div></div><a className="repo-link" href="https://github.com/Geethik26/atlas-compliance" target="_blank" rel="noreferrer">Repository & documentation <ArrowUpRight size={15}/></a></aside>
 <div className="main-area"><header className="topbar"><div className="crumb">Minimum wage <ChevronRight size={14}/><strong>{tab}</strong></div><span className="prototype">ASSESSMENT PROTOTYPE</span></header><main>
 <div className="page-title"><div><p className="eyebrow">ASTERIA / BELLWETHER</p><h1>{tab==='Overview'?'Compliance overview':tab}</h1><p className="sub">Every decision starts with a published source and a reviewed rule.</p></div><Button variant="outline" disabled={blocked} onClick={()=>download('atlas-evidence.json',{simulation:mode==='replay',workspace:mode,evaluation_date:date,files:files.current})}><Download/>Export evidence</Button></div>
 <div className="controls"><div className="mode-switch"><button className={mode==='live'?'chosen':''} disabled={blocked} onClick={()=>{setSelected(null);run('view',{},'live','2026-09-21')}}>Live sources</button><button className={mode==='replay'?'chosen':''} disabled={blocked} onClick={()=>{setSelected(null);run('view',{},'replay','2027-01-01')}}>Simulated replay</button></div><label className="date-label">Evaluation date<input aria-label="Evaluation date" type="date" value={date} disabled={blocked} onChange={e=>{if(e.target.value)run('evaluate',{},mode,e.target.value)}}/></label><Button disabled={blocked} onClick={()=>run(mode==='live'?'monitor':'stage_demo')}>{mode==='live'?<RefreshCw/>:<Play/>}{mode==='live'?'Check sources':'Stage change'}</Button></div>
 {error&&<div className="notice danger" role="alert"><AlertTriangle size={20}/>{error}</div>}{busy&&<div className="notice loading" role="status"><RefreshCw className="spin" size={18}/>{busy}</div>}{!busy&&<div className={'notice '+(mode==='replay'?'simulation':'')}><ShieldCheck size={18}/><span>{mode==='replay'?'Simulated scenario. Seeded rates and fixture publications are isolated from the live workspace.':'Live workspace. Captured publications require your review; no rule is approved automatically.'}</span>{saved&&<small>Saved {saved}</small>}</div>}
 {tab==='Overview'&&<><section className="stats"><div className="stat"><span>Employees evaluated</span><strong>{data?.record_count??'—'}</strong><small>Supplied synthetic dataset</small></div><div className="stat flag"><span>Underpaid employees</span><strong>{summary.NON_COMPLIANT||0}</strong><small>{summary.COMPLIANT||0} meet the approved minimum</small></div><div className="stat"><span>Awaiting rule review</span><strong>{pending.length}</strong><small>{summary.INSUFFICIENT_DATA||0} results need approved data</small></div><div className="stat"><span>Estimated weekly shortfall</span><strong><em>AST</em> {money(exposure)}</strong><small>Scheduled hours · estimates only</small></div></section>
 {pending.length>0&&<div className="review-banner"><div><FileCheck2 size={23}/><div><strong>{pending.length} publications are ready for review</strong><p>Inspect the source, effective date, and scope before approving.</p></div></div><Button variant="outline" onClick={()=>setTab('Rule review')}>Open review queue <ChevronRight/></Button></div>}
 <section className="panel"><div className="panel-heading"><div><h2>Employee results</h2><p>